services:
  iam-service:
    build:
      context: ./apps/services/iam-service
      dockerfile: Dockerfile
    container_name: iam-service
    env_file:
      - .env
    environment:
      - SERVER_PORT=8081
      - ENABLE_PREFORK=false
      - DB_HOST=gradeloop-gradeloop-project-v2.k.aivencloud.com
      - DB_PORT=17317
      - DB_USER=avnadmin
      - DB_PASSWORD=${GRA_DB_PASSWORD}
      - DB_NAME=defaultdb
      - DB_SSLMODE=require
    ports:
      - "8081:8081"
    networks:
      - gradeloop-network

  api-gateway:
    image: krakend:latest
    container_name: api-gateway
    volumes:
      - ./apps/gateway/krakend.json:/etc/krakend/krakend.json
    ports:
      - "8080:8080"
    command: [ "run", "-c", "/etc/krakend/krakend.json" ]
    depends_on:
      - iam-service
    networks:
      - gradeloop-network

networks:
  gradeloop-network:
    driver: bridge
